
apiVersion: v1
kind: Service
metadata:
  name: weblintheatre
  namespace: default
  labels:
    run: weblintheatre
spec:
  selector:
    run: weblintheatre
  ports:
  - name: http
    port: 8401
    protocol: TCP

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: weblintheatre-ingress-a
  namespace: default
  annotations:
      haproxy.org/check: "true"
      haproxy.org/forwarded-for: "true"
      haproxy.org/ssl-redirect: "true"
      haproxy.org/load-balance: "roundrobin"
spec:
  tls:
  - hosts:
    - weblintheatre.k8s.sui.li
    secretName: default/tls-secret
    #- theatre.weblin.sui.li
    #secretName: default/tls-weblin-sui-li
  rules:
  - host: weblintheatre.k8s.sui.li
    http:
      paths:
      - path: /
        backend:
          serviceName: weblintheatre
          servicePort: 8401


---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: weblintheatre-ingress-b
  namespace: default
  annotations:
      haproxy.org/check: "true"
      haproxy.org/forwarded-for: "true"
      haproxy.org/ssl-redirect: "true"
      haproxy.org/load-balance: "roundrobin"
spec:
  tls:
  - hosts:
    - theatre.weblin.sui.li
    secretName: default/tls-weblin-sui-li
  rules:
  - host: theatre.weblin.sui.li
    http:
      paths:
      - path: /
        backend:
          serviceName: weblintheatre
          servicePort: 8401
