apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblintheatre
  namespace: default
spec:
  selector:
    matchLabels:
      run: weblintheatre
  replicas: 1
  template:
    metadata:
      labels:
        run: weblintheatre
    spec:
      containers:
        - name: weblintheatre
          image: docker.k8s.sui.li/weblintheatre:latest
          ports:
            - containerPort: 8401
              protocol: TCP
          env:
            - name: NODE_ENV
              value: prod
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"

---
apiVersion: v1
kind: Service
metadata:
  name: weblintheatre
  namespace: default
  labels:
    run: weblintheatre
  annotations:
    haproxy.org/check: "true"
    haproxy.org/forwarded-for: "enabled"
    haproxy.org/load-balance: "roundrobin"
spec:
  selector:
    run: weblintheatre
  ports:
  - name: http
    port: 8401
    protocol: TCP

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: weblintheatre-ingress
  namespace: default
spec:
  rules:
  - host: weblintheatre.k8s.sui.li
    http:
      paths:
      - path: /
        backend:
          serviceName: weblintheatre
          servicePort: 8401
