apiVersion: v1
kind: Secret
metadata:
  name: aws-key
  namespace: suat
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQTNBUVZGWk03WDc2SERKVjMKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0geVkySDVBaldldjBEand5ZkpFbUFkS21yS2tRVVlmaFQwT2ozNmtLSwo=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weblintheatre
  namespace: suat
spec:
  selector:
    matchLabels:
      run: weblintheatre
  replicas: 1
  template:
    metadata:
      labels:
        run: weblintheatre
    spec:
      containers:
        - name: weblintheatre
          image: docker.k8s.sui.li/weblintheatre:5e999b48
          ports:
            - containerPort: 8401
              protocol: TCP
          env:
            - name: NODE_ENV
              value: prod
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: "0"
          volumeMounts:
          - name: aws-key
            readOnly: true
            mountPath: "/root/.aws"


      volumes:
      - name: aws-key
        secret:
          secretName: aws-key
          defaultMode: 0400

---
apiVersion: v1
kind: Service
metadata:
  name: weblintheatre
  namespace: suat
  labels:
    run: weblintheatre
spec:
  selector:
    run: weblintheatre
  ports:
  - name: http
    port: 8401
    protocol: TCP


