apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: weblintheatre-ingress-b
  namespace: suat
  annotations:
    haproxy.org/check: "true"
    haproxy.org/forwarded-for: "true"
    haproxy.org/ssl-redirect: "true"
    haproxy.org/load-balance: "roundrobin"
spec:
  tls:
  - hosts:
    - weblintheatre.sui.li
    secretName: devops/tls-sui-li
  rules:
  - host: weblintheatre.sui.li
    http:
      paths:
      - path: /
        backend:
          serviceName: weblintheatre
          servicePort: 8401